### ISSUE TITLE
Sensitive Values - Breaking change

### ISSUE THREAD

**Issue by spammads** [devopsarr/terraform-provider-lidarr#202]
Hi,
I get the same errors as described here: https://github.com/devopsarr/terraform-provider-radarr/issues/222

Can you please also provide a fix for this?
Thanks.
Br.

**Comment by Fuochi** [comment]
Hi @spammads,
Thanks for opening this, I'll address the issue in #201.

**Comment by spammads** [comment]
No problem. I checked it. It works. Thanks!
